In [2]:
import numpy as np

Creación y Indexación:
Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [3]:
array = np.random.randint(10, 100, 50)
array_multiplo_5 = array[ : : 5]
array_multiplo_5

array([87, 18, 10, 38, 57, 17, 30, 58, 52, 86])

In [4]:
array1 = np.random.randint(1, 21 , size= 30)
print(array1)
array_impares = array1[: : 2]
print(array_impares)

[17  5 16 11  6 16  7  5  8 20 16  4  5 19  1  5  5 17 16 13 17 15  3  8
  9 16 11  9  1  8]
[17 16  6  7  8 16  5  1  5 16 17  3  9 11  1]


In [5]:
'''Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1).
Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.'''

array_bi = np.random.rand(4,6) *5
array_bi



array([[2.19666276, 4.03485999, 4.99263912, 2.98082571, 0.53543476,
        0.5337588 ],
       [4.01691962, 4.07026459, 2.13955341, 2.07216473, 1.52979465,
        3.72418354],
       [4.79972712, 1.14966504, 2.27584273, 4.91651356, 2.5052438 ,
        4.71490815],
       [2.18051596, 1.31036613, 4.00132401, 0.03823094, 2.91337649,
        4.82536009]])

In [6]:
array_bi_2d = np.round(array_bi, 2)
array_bi_2d


array([[2.2 , 4.03, 4.99, 2.98, 0.54, 0.53],
       [4.02, 4.07, 2.14, 2.07, 1.53, 3.72],
       [4.8 , 1.15, 2.28, 4.92, 2.51, 4.71],
       [2.18, 1.31, 4.  , 0.04, 2.91, 4.83]])

In [7]:
ultima_fila = array_bi_2d[-1]
ultima_fila

array([2.18, 1.31, 4.  , 0.04, 2.91, 4.83])

In [8]:
#BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). 
# Reemplaza los elementos en posiciones múltiplos de 3 por 0.


# Creo el array 3D
array_3d = np.random.randint(0, 101, size=(2, 3, 5))
print("Array original:")
print(array_3d)

# Aplano el array para facilitar el reemplazo
array_flat = array_3d.flatten()

# Reemplazo elementos en posiciones múltiplos de 3 por 0
array_flat[::3] = 0

# le vuelvo a dar la forma original al array
array_3d_modified = array_flat.reshape((2, 3, 5))

print("Array modificado:")
print(array_3d_modified)



Array original:
[[[ 9 52 76 27 38]
  [21 18 74 55 62]
  [11 68 75 69 36]]

 [[45 44 86 63 56]
  [50 96 37 51 14]
  [20 11 67 73 83]]]
Array modificado:
[[[ 0 52 76  0 38]
  [21  0 74 55  0]
  [11 68  0 69 36]]

 [[ 0 44 86  0 56]
  [50  0 37 51  0]
  [20 11  0 73 83]]]


Ejercicios con reshape:
Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

Ejercicios con transpose:
Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

Preguntas teóricas:
¿Qué diferencia existe entre el reshape y el transpose?

¿Y entre el transpose y el swapaxes?

Funciones Aritméticas y Estadísticas:
Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [9]:
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])

SyntaxError: unmatched ')' (1174397853.py, line 8)